/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_aio4c_Aio4c */

#ifndef _Included_com_aio4c_Aio4c
#define _Included_com_aio4c_Aio4c
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_aio4c_Aio4c
 * Method:    usage
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_aio4c_Aio4c_usage
  (JNIEnv *, jclass);

/*
 * Class:     com_aio4c_Aio4c
 * Method:    init
 * Signature: ([Ljava/lang/String;Lcom/aio4c/log/Logger;)V
 */
JNIEXPORT void JNICALL Java_com_aio4c_Aio4c_init
  (JNIEnv *, jclass, jobjectArray, jobject);

/*
 * Class:     com_aio4c_Aio4c
 * Method:    end
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_aio4c_Aio4c_end
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
