/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_aio4c_buffer_Buffer */

#ifndef _Included_com_aio4c_buffer_Buffer
#define _Included_com_aio4c_buffer_Buffer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_aio4c_buffer_Buffer
 * Method:    array
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_aio4c_buffer_Buffer_array__
  (JNIEnv *, jobject);

/*
 * Class:     com_aio4c_buffer_Buffer
 * Method:    array
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_com_aio4c_buffer_Buffer_array___3B
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_aio4c_buffer_Buffer
 * Method:    get
 * Signature: ()B
 */
JNIEXPORT jbyte JNICALL Java_com_aio4c_buffer_Buffer_get
  (JNIEnv *, jobject);

/*
 * Class:     com_aio4c_buffer_Buffer
 * Method:    getShort
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_com_aio4c_buffer_Buffer_getShort
  (JNIEnv *, jobject);

/*
 * Class:     com_aio4c_buffer_Buffer
 * Method:    getInt
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_aio4c_buffer_Buffer_getInt
  (JNIEnv *, jobject);

/*
 * Class:     com_aio4c_buffer_Buffer
 * Method:    getLong
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_aio4c_buffer_Buffer_getLong
  (JNIEnv *, jobject);

/*
 * Class:     com_aio4c_buffer_Buffer
 * Method:    getFloat
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_aio4c_buffer_Buffer_getFloat
  (JNIEnv *, jobject);

/*
 * Class:     com_aio4c_buffer_Buffer
 * Method:    getDouble
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_com_aio4c_buffer_Buffer_getDouble
  (JNIEnv *, jobject);

/*
 * Class:     com_aio4c_buffer_Buffer
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_aio4c_buffer_Buffer_getString
  (JNIEnv *, jobject);

/*
 * Class:     com_aio4c_buffer_Buffer
 * Method:    put
 * Signature: (B)V
 */
JNIEXPORT void JNICALL Java_com_aio4c_buffer_Buffer_put
  (JNIEnv *, jobject, jbyte);

/*
 * Class:     com_aio4c_buffer_Buffer
 * Method:    putShort
 * Signature: (S)V
 */
JNIEXPORT void JNICALL Java_com_aio4c_buffer_Buffer_putShort
  (JNIEnv *, jobject, jshort);

/*
 * Class:     com_aio4c_buffer_Buffer
 * Method:    putInt
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_aio4c_buffer_Buffer_putInt
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_aio4c_buffer_Buffer
 * Method:    putLong
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_aio4c_buffer_Buffer_putLong
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_aio4c_buffer_Buffer
 * Method:    putFloat
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_aio4c_buffer_Buffer_putFloat
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_aio4c_buffer_Buffer
 * Method:    putDouble
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_com_aio4c_buffer_Buffer_putDouble
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     com_aio4c_buffer_Buffer
 * Method:    putString
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_aio4c_buffer_Buffer_putString
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_aio4c_buffer_Buffer
 * Method:    hasRemaining
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_aio4c_buffer_Buffer_hasRemaining
  (JNIEnv *, jobject);

/*
 * Class:     com_aio4c_buffer_Buffer
 * Method:    position
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_aio4c_buffer_Buffer_position__
  (JNIEnv *, jobject);

/*
 * Class:     com_aio4c_buffer_Buffer
 * Method:    position
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_aio4c_buffer_Buffer_position__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_aio4c_buffer_Buffer
 * Method:    limit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_aio4c_buffer_Buffer_limit__
  (JNIEnv *, jobject);

/*
 * Class:     com_aio4c_buffer_Buffer
 * Method:    limit
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_aio4c_buffer_Buffer_limit__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_aio4c_buffer_Buffer
 * Method:    capacity
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_aio4c_buffer_Buffer_capacity
  (JNIEnv *, jobject);

/*
 * Class:     com_aio4c_buffer_Buffer
 * Method:    flip
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_aio4c_buffer_Buffer_flip
  (JNIEnv *, jobject);

/*
 * Class:     com_aio4c_buffer_Buffer
 * Method:    reset
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_aio4c_buffer_Buffer_reset
  (JNIEnv *, jobject);

/*
 * Class:     com_aio4c_buffer_Buffer
 * Method:    allocate
 * Signature: (I)Lcom/aio4c/buffer/Buffer;
 */
JNIEXPORT jobject JNICALL Java_com_aio4c_buffer_Buffer_allocate
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_aio4c_buffer_Buffer
 * Method:    toString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_aio4c_buffer_Buffer_toString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
