/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_aio4c_Client */

#ifndef _Included_com_aio4c_Client
#define _Included_com_aio4c_Client
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_aio4c_Client
 * Method:    initialize
 * Signature: (Lcom/aio4c/ClientConfig;Lcom/aio4c/ConnectionFactory;)V
 */
JNIEXPORT void JNICALL Java_com_aio4c_Client_initialize
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_aio4c_Client
 * Method:    start
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_aio4c_Client_start
  (JNIEnv *, jobject);

/*
 * Class:     com_aio4c_Client
 * Method:    join
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_aio4c_Client_join
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
