/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_aio4c_Connection */

#ifndef _Included_com_aio4c_Connection
#define _Included_com_aio4c_Connection
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_aio4c_Connection
 * Method:    enableWriteInterest
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_aio4c_Connection_enableWriteInterest
  (JNIEnv *, jobject);

/*
 * Class:     com_aio4c_Connection
 * Method:    close
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_aio4c_Connection_close
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_aio4c_Connection
 * Method:    closing
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_aio4c_Connection_closing
  (JNIEnv *, jobject);

/*
 * Class:     com_aio4c_Connection
 * Method:    toString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_aio4c_Connection_toString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
