/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_aio4c_log_Log */

#ifndef _Included_com_aio4c_log_Log
#define _Included_com_aio4c_log_Log
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_aio4c_log_Log
 * Method:    log
 * Signature: (Lcom/aio4c/log/Log/Level;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_aio4c_log_Log_log
  (JNIEnv *, jclass, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_aio4c_log_Log_Level */

#ifndef _Included_com_aio4c_log_Log_Level
#define _Included_com_aio4c_log_Log_Level
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
