/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_aio4c_Server */

#ifndef _Included_com_aio4c_Server
#define _Included_com_aio4c_Server
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_aio4c_Server
 * Method:    initialize
 * Signature: (Lcom/aio4c/ServerConfig;Lcom/aio4c/ConnectionFactory;)V
 */
JNIEXPORT void JNICALL Java_com_aio4c_Server_initialize
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_aio4c_Server
 * Method:    start
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_aio4c_Server_start
  (JNIEnv *, jobject);

/*
 * Class:     com_aio4c_Server
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_aio4c_Server_stop
  (JNIEnv *, jobject);

/*
 * Class:     com_aio4c_Server
 * Method:    join
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_aio4c_Server_join
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
